minecraftVersion=1.21.11
yarnMappings=1.21.11+build.1
loaderVersion=0.17.3
fabricApiVersion=0.139.5+1.21.11
modMenuVersion=17.0.0
clothConfigVersion=21.11.153
minecraftDependency=1.21.11
javaDependency=>=17
javaRelease=17
